name: Continuous Delivery - Inventory LUA

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: windows-latest
    env:
      BundleFileName: "inventory.zip"
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Create Bundle  
      shell: bash
      run: |
        # Pack files
        mkdir inventory
        mkdir inventory/client
        mkdir inventory/common
        cp *.lua inventory/
        cp -r client/*.lua inventory/client/
        cp -r common/*.lua inventory/common/
        7z a -r -tzip $BundleFileName inventory/*.lua
        7z a -tzip $BundleFileName utils/*.lua

    - name: Publish
      uses: softprops/action-gh-release@v1
      with:
        files: "*.zip"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# https://github.com/marketplace/actions/easy-zip-files        
